<?php
// $Id$

/**
 * @file
 * Adds a Read: Now | Later button for nodes
 */

/**
 * Implements hook_init().
 */
function readability_init() {
  if (variable_get('readability_verify_domain', 0)) {
    $verification = array(
      '#type' => 'markup',
      '#markup' => variable_get('readability_verification'),
    );
    drupal_add_html_head($verification, 'readability_verification');
  }
}

/**
 * Implements hook_permission().
 */
function readability_permission() {
  return array(
    'administer readability' =>  array(
      'title' => t('Administer Readability settings'),
      'description' => t('Change the weight and node types on which the button appears'),
    ),
    'access readability button' => array(
      'title' => t('Access Readability button'),
    )
  );
}

/**
 * Implements hook_menu().
 */
function readability_menu() {
  $items = array();
  $items['admin/config/services/readability'] = array(
    'title' => 'Readability Button',
    'description' => 'Configure the look and behavior of the Readability Button on the site.',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('readability_admin_settings'),
    'access arguments' => array('administer readability'),
    'file' => 'readability.admin.inc',
    'type' => MENU_NORMAL_ITEM,
  );
  return $items;
}

/**
 * Implementation of hook_theme()
 */
function readability_theme() {
	return array(
    'readability_display' => array(
      'variables' => array('object' => NULL, 'options' => array()),
    ),
  );
}

/**
 * Implements hook_node_view().
 */
function readability_node_view($node, $view_mode, $langcode) {
  $enable_readability = variable_get('readability_button_enable_' . $node->type, 0);
  if ($enable_readability && $view_mode == 'full' && user_access('access readability')) {
    $node->content['readability'] = array(
      '#object' => $node,
      '#weight' => variable_get('readability_button_weight_' . $node->type, 0),
      '#theme' => 'readability_display__' . $node->type,
    );
  }
}

function theme_readability_display($variables) {
  $readability = "<div id='rdbWrapper'></div><script type='text/javascript'>
  (function() {
      var s     = document.getElementsByTagName('script')[0],
          rdb   = document.createElement('script');
      rdb.type  = 'text/javascript';
      rdb.async = true;
      rdb.src   = document.location.protocol + '//www.readability.com/embed.js';
      s.parentNode.insertBefore(rdb, s);
  })();
  </script>";
  return $readability; 
}


function readability_form_node_type_form_alter(&$form, $form_state) {
  $form['readability'] = array(
    '#type' => 'fieldset',
    '#title' => 'Readability settings',
    '#weight' => 25,
    '#group' => 'additional_settings',
  );
  $form['readability']['button'] = array(
      '#type' => 'fieldset',
      '#title' => 'Readability button settings',
      '#collapsible' => FALSE,
      '#collapsed' => FALSE,
      '#weight' => 1,
      '#group' => 'readability',
  );
  $form['readability']['button']['readability_button_enable'] = array(
    '#type' => 'checkbox',
    '#title' => t('Enable readability button'),
    '#default_value' => variable_get('readability_button_enable_' . $form['#node_type']->type, 0),
    '#description' => t('Check this box to enable the Readability button for this node type.'),    
  );
  $form['readability']['button']['readability_button_weight'] = array(
    '#type' => 'select',
    '#default_value' => variable_get('readability_button_weight_' . $form['#node_type']->type, 0),
    '#options' => drupal_map_assoc(range(-10, 10)),
  );
}